### ISSUE TITLE
Matrix Nextcloud

### ISSUE THREAD

**Issue by select** [poVoq/conversejs-ubports#17]
Sorry to bother you here, but the repo in question is archived and github doese not have private messaging.

I saw your question regardin connecting Matrix Synapse with Nextcloud and wanted to ask you if you had any success doing that?

You can reach me on matrix @select:matrix.org

**Comment by poVoq** [comment]
Sorry, no. I am not actively looking into anything Matrix related anymore given that I don't agree with some of their technological and business choices.
