### ISSUE TITLE
unable to login with jabster account

### ISSUE THREAD

**Issue by lindsayb37** [poVoq/conversejs-ubports#21]
I have an account with @jabster.pl server from website http://jabbim.com.

When I put in my account credentials I get the spinning wheel and never go any further. Any help would be appreciated.

**Comment by poVoq** [comment]
You need to enter `wss://jabb.im/websocket/` as the websocket server setting.

**Comment by lindsayb37** [comment]
> You need to enter `wss://jabb.im/websocket/` as the websocket server setting.

You are the man! (or woman?) I appreciate the help. Also, I had to do Automatic login or it still just spun the wheel. Thanks again.
