### ISSUE TITLE
s/encyption/encryption/ on https://open-store.io/app/conversejs.povoq

### ISSUE THREAD

**Issue by arthurzenika** [poVoq/conversejs-ubports#8]

**Comment by poVoq** [comment]
Sorry, what do you want to say? OMEMO encryption is supported and working.

**Comment by arthurzenika** [comment]
I was just reporting a typo in the description on open-store.io

**Comment by poVoq** [comment]
Uhh, yes. Thanks for reporting and fixed now :)
